*** Variables ***
${EDIT_IFRAME}                 xpath=//iframe[contains(@src, '/page/album/')]
${EDIT_FORM}                   xpath=//form[.//input[@name='editMode']]
${EDIT_EAN}                    xpath=${EDIT_FORM}//input[@name='ean' and @readonly]
${EDIT_TITLE}                  xpath=${EDIT_FORM}//input[@name='title']
${EDIT_LANGUAGE}               xpath=${EDIT_FORM}//select[@name='language']
${EDIT_LABEL}                  xpath=${EDIT_FORM}//select[@name='label_id']
${EDIT_GENRE}                  xpath=${EDIT_FORM}//input[@name='genre']
${EDIT_RELEASE_DATE}           xpath=${EDIT_FORM}//input[@name='release_date_dig']
${EDIT_EXPIRATION_DATE}        xpath=${EDIT_FORM}//input[@name='expire_date']
${EDIT_PRICE_CODE}             xpath=${EDIT_FORM}//select[@name='pricecode']
${EDIT_ITUNES_PRICE_CODE}      xpath=${EDIT_FORM}//select[@name='pricecode_itunes']
${EDIT_C_LINE_YEAR}            xpath=${EDIT_FORM}//input[@name='c_line_year']
${EDIT_C_LINE_TEXT}            xpath=${EDIT_FORM}//input[@name='c_line_text']
${EDIT_P_LINE_YEAR}            xpath=${EDIT_FORM}//input[@name='p_line_year']
${EDIT_P_LINE_TEXT}            xpath=${EDIT_FORM}//input[@name='p_line_text']
${EDIT_COVER_FILE}             xpath=${EDIT_FORM}//input[@name='file' and @type='file']
${EDIT_COVER_UPLOAD}           xpath=${EDIT_FORM}//button[normalize-space()='Upload File']
${EDIT_CONTRIBUTOR_ROW}        xpath=${EDIT_FORM}//tr[contains(@class,'js-dmb-cce__item') and not(contains(@style,'display: none')) and normalize-space(.//span[contains(@class,'dmb-js-artist-name')])!='']
${EDIT_REMOVE_CONTRIBUTOR}     xpath=(${EDIT_CONTRIBUTOR_ROW}//td[contains(@class,'dmb-js-cce__btn-remove')])[1]
${EDIT_CONTRIBUTOR_NAME}       xpath=${EDIT_FORM}//input[@name='newArtist']
${EDIT_CONTRIBUTOR_ROLES}      xpath=(${EDIT_FORM}//select[starts-with(@name,'cce_aRoles[')])[last()]
${EDIT_ADD_CONTRIBUTOR}        xpath=${EDIT_FORM}//button[contains(@class,'dmb-js-cce__add-btn')]
${EDIT_AJAX_OPTION}            xpath=//table[contains(@class,'vc-js-ajax-result-list')]//td[normalize-space()="__VALUE__"]
${EDIT_SAVE_ACTION}            xpath=//a[contains(@onclick,'"action":"save"')]
${EDIT_PUBLISH_ACTION}         xpath=//a[contains(@onclick,'"action":"publish"')]
${EDIT_SUCCESS}                xpath=//*[contains(@class,'success') and (contains(normalize-space(.),'saved') or contains(normalize-space(.),'published'))]

${TRACK_EDIT_IFRAME}           xpath=//iframe
${TRACK_EDIT_ACTION}           xpath=//li[.//*[normalize-space()='Edit Metadata']]
${TRACK_EDIT_FORM}             xpath=//form[.//input[@name='targetAlbumId']]
${TRACK_EDIT_NEXT}             xpath=(//button[normalize-space()='Next' and not(@disabled)])[last()]
${TRACK_EDIT_TITLE}            xpath=${TRACK_EDIT_FORM}//input[@name='title']
${TRACK_EDIT_GENRE}            xpath=${TRACK_EDIT_FORM}//input[@name='genre']
${TRACK_EDIT_EXPLICIT}         xpath=${TRACK_EDIT_FORM}//select[@name='explicitContentFlag']
${TRACK_EDIT_P_YEAR}           xpath=${TRACK_EDIT_FORM}//input[@name='pLine_year']
${TRACK_EDIT_P_TEXT}           xpath=${TRACK_EDIT_FORM}//input[@name='pLine_text']
${TRACK_EDIT_FIELD_TITLE}      xpath=${TRACK_EDIT_FORM}//input[@name='sel_fields[]' and @value='title']
${TRACK_EDIT_FIELD_GENRE}      xpath=${TRACK_EDIT_FORM}//input[@name='sel_fields[]' and @value='genre_id']
${TRACK_EDIT_FIELD_EXPLICIT}   xpath=${TRACK_EDIT_FORM}//input[@name='sel_fields[]' and @value='explicitContentFlag']
${TRACK_EDIT_FIELD_P_LINE}     xpath=${TRACK_EDIT_FORM}//input[@name='sel_fields[]' and @value='pLine']
${TRACK_EDIT_FIELD_CONTRIBUTORS}    xpath=${TRACK_EDIT_FORM}//input[@name='sel_fields[]' and @value='contributors']
${TRACK_EDIT_CONTRIBUTOR_MODE}      xpath=${TRACK_EDIT_FORM}//select[@name='contributorMode']
${TRACK_EDIT_CONTRIBUTOR_ROW}       xpath=${TRACK_EDIT_FORM}//tr[contains(@class,'js-dmb-cce__item') and not(contains(@style,'display: none')) and normalize-space(.//span[contains(@class,'dmb-js-artist-name')])!='']
${TRACK_EDIT_REMOVE_CONTRIBUTOR}    xpath=(${TRACK_EDIT_CONTRIBUTOR_ROW}//td[contains(@class,'dmb-js-cce__btn-remove')])[1]
${TRACK_EDIT_CONTRIBUTOR_NAME}      xpath=${TRACK_EDIT_FORM}//input[@name='newArtist']
${TRACK_EDIT_CONTRIBUTOR_ROLES}     xpath=(${TRACK_EDIT_FORM}//select[starts-with(@name,'cce_aRoles[')])[last()]
${TRACK_EDIT_ADD_CONTRIBUTOR}       xpath=${TRACK_EDIT_FORM}//button[contains(@class,'dmb-js-cce__add-btn')]
${TRACK_EDIT_SELECTED_TRACK}   xpath=${TRACK_EDIT_FORM}//input[@name='selectedTargetTrackIds[]' and @checked]
${TRACK_EDIT_SAVE}             xpath=${TRACK_EDIT_FORM}//button[normalize-space()='Save']
